[package]
name = "complete-cli"
version = "0.1.0"
authors = ["ashtneoi <ashtneoi@gmail.com>"]
edition = "2018"
license = "MIT"

[dependencies]
abbrev-tree = { version = "0.1.1", features = ["serde"] }
bincode = "1.1.2"
directories = "1.0.2"
serde = { version = "1.0.89", features = ["derive"] }
